### PR TITLE
Layout Alterations 

### PR DESCRIPTION
**Pull request by zaaakk**

### CODE REVIEW

**Comment by bcail** [comment]
Hey Zak, looks like some hidden files from your .idea/ directory got into the PR... Could you please remove those from the PR? Let me know if you have questions about that.

**Comment by zaaakk** [comment]
Did that do the trick?

**Comment by bcail** [comment]
I don't see the .idea files anymore, but it looks like app_settings.py got removed (that's what caused the automatic tests to fail). Can you add app_settings.py back in?

**Comment by zaaakk** [comment]
Oops. Shouldn't have ignored that one!

**Comment by bcail** [comment]
Looks like the tests have passed. Merging.

**Pull request merged**
